# Generated by Django 4.1.5 on 2023-04-30 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('BY', 'buy'), ('SL', 'sell'), ('RT', 'rent')], max_length=2)),
                ('area_formating', models.CharField(choices=[('TE', 'terai'), ('HM', 'hilly and mountain')], max_length=2)),
                ('area1', models.IntegerField()),
                ('area2', models.IntegerField()),
                ('area3', models.IntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('property_type', models.CharField(choices=[('H', 'house'), ('L', 'land')], max_length=1)),
                ('no_of_bedrooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('no_of_floor', models.IntegerField()),
                ('parking_area', models.PositiveIntegerField()),
                ('facing_side', models.CharField(max_length=2)),
                ('built_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='API/images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
        ),
    ]
