# Generated by Django 4.1.5 on 2023-05-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='street',
        ),
        migrations.AlterField(
            model_name='post',
            name='facing_side',
            field=models.CharField(max_length=100),
        ),
    ]
