# Generated by Django 4.2.1 on 2024-02-17 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='area1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='area2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='area3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='area_formating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='built_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='facing_side',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_bathrooms',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_bedrooms',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_floor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parking_area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='property_type',
        ),
        migrations.AddField(
            model_name='post',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
