# Generated by Django 4.1.5 on 2023-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
