# Generated by Django 4.2.1 on 2024-02-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_recommendation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='post',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
