# Generated by Django 4.2.1 on 2024-02-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPT',
            new_name='OTP',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='opt_number',
            new_name='otp_number',
        ),
    ]
