# Generated by Django 4.2.1 on 2024-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='purpose',
            field=models.CharField(choices=[('SL', 'sell'), ('RT', 'rent')], max_length=2),
        ),
        migrations.AlterField(
            model_name='land',
            name='purpose',
            field=models.CharField(choices=[('SL', 'sell'), ('RT', 'rent')], max_length=2),
        ),
    ]
